//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.SRVReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRVReference.ISRV")]
    public interface ISRV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRV/GetDis", ReplyAction="http://tempuri.org/ISRV/GetDisResponse")]
        double GetDis(double sourceLng, double sourceLat, double toLng, double toLat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISRV/GetDis", ReplyAction="http://tempuri.org/ISRV/GetDisResponse")]
        System.Threading.Tasks.Task<double> GetDisAsync(double sourceLng, double sourceLat, double toLng, double toLat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISRVChannel : BL.SRVReference.ISRV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRVClient : System.ServiceModel.ClientBase<BL.SRVReference.ISRV>, BL.SRVReference.ISRV {
        
        public SRVClient() {
        }
        
        public SRVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetDis(double sourceLng, double sourceLat, double toLng, double toLat) {
            return base.Channel.GetDis(sourceLng, sourceLat, toLng, toLat);
        }
        
        public System.Threading.Tasks.Task<double> GetDisAsync(double sourceLng, double sourceLat, double toLng, double toLat) {
            return base.Channel.GetDisAsync(sourceLng, sourceLat, toLng, toLat);
        }
    }
}
